// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyBo7HoQasn2Bm7pZHrcBsdSFaYgj0bMPZk',
    appId: '1:791307120893:ios:301b9a583447a7ec6c4e94',
    messagingSenderId: '791307120893',
    projectId: 'rando-app-highlanderkev',
    authDomain: 'rando-app-highlanderkev.firebaseapp.com',
    storageBucket: 'rando-app-highlanderkev.appspot.com',
    measurementId: 'G-1C0F7JQNR8',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyDWoZ7tYGNRnnU8d4tnWDOuP1H_3lko93U',
    appId: '1:791307120893:ios:301b9a583447a7ec6c4e94',
    messagingSenderId: '791307120893',
    projectId: 'rando-app-highlanderkev',
    storageBucket: 'rando-app-highlanderkev.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyAwPUIUNeQxN4TYnKDGDi789kji2o5kFd8',
    appId: '1:791307120893:ios:301b9a583447a7ec6c4e94',
    messagingSenderId: '791307120893',
    projectId: 'rando-app-highlanderkev',
    storageBucket: 'rando-app-highlanderkev.appspot.com',
    iosClientId:
        '791307120893-vqh8pfnm08f1rkshjvtdj6rvvdnh708s.apps.googleusercontent.com',
    iosBundleId: 'com.example.randoApp',
  );

  static FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'AIzaSyAwPUIUNeQxN4TYnKDGDi789kji2o5kFd8',
    appId: '1:791307120893:ios:301b9a583447a7ec6c4e94',
    messagingSenderId: '791307120893',
    projectId: 'rando-app-highlanderkev',
    storageBucket: 'rando-app-highlanderkev.appspot.com',
    iosClientId:
        '791307120893-vlfipvcrper9ljhufs7f7dcmmfnjcrbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.randoApp.RunnerTests',
  );
}
